apiVersion: apps/v1
kind: Deployment
metadata:
  name: sverker-hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sverker-hello-world
  template:
    metadata:
      labels:
        app: sverker-hello-world
    spec:
      containers:
        - name: sverker-hello-world-container
          image: devazregistry.azurecr.io/sve-hello-world-dotnet:latest
          ports:
            - containerPort: 3000
